### ISSUE TITLE
Uniform frontend

### ISSUE THREAD

**Issue by wildeyes** [DataHackIL/ninjathon#28]
How are we going to maintain the same design if each provider uses his own project / scaffolding / etc..?

**Comment by wildeyes** [comment]
@shakedlokits

**Comment by oryanmoshe** [comment]
I think we should use an existing UI framework for most of the heavy lifting (I thought about material-ui)\
And in general we should probably go for a micro-frontend design, using one wrapping app and having each provider rendered as needed.\
That way we can share components between the providers as well.
