### ISSUE TITLE
User profile design [Users]

### ISSUE THREAD

**Issue by oryanmoshe** [DataHackIL/ninjathon#30]
# User Profile
## What's a user
In our system a "user" is anyone who uses the system, and they're separated into different roles:
- Hacker (competitor)
- Mentor
- Judge
- Admin

Each user uses the system differently, according to their role.\
For example, a Judge can grade a team, and a Hacker can be a part of a team.

#### Registration
The user enters his basic details (**email**, **password**, **name**, CV, picture)\
A user is created in the database using the email and the password\
The user is updated with his role, and any additional inputs he provided in the registration form\
A JWT token containing the user's permissions is generated and returned to the client as a session cookie

Registration page implemented in #25 \
Updating capability implemented in #29 

#### Login
The user enters his email and password\
The login details are checked against the database\
If they're correct, a JWT token is generated and returned to the client as a session cookie

#### View & Update
The user can go to his profile page and view his details\
The user can update his different attributes by editing his profile page

#### Password Reset
In case the user forgot his password he can click a "reset password" button\
The user enters his email address\
The user gets an email containing a one-time link allowing him to reset his password\
The password is updated in the database

#### Team Creation + Editing
A hacker can create a team, which is a group of multiple hackers

#### Team Joining
A hacker can search for a team to join (if this team is public)\
A hacker can join a team by invitation

#### Mentor Feedback
A user can give feedback about a mentor

#### Feedbacks
A mentor can read the feedback he received

#### Judging
A judge can see the teams he has to judge and their location\
A judge can rate each team in different parameters

### Admin Flows
An admin can do everything.

**Comment by shakedlokits** [comment]
This looks great, @wildeyes did you look through this?

1. Should we add `Staff`? for the roles? we will need to go trough CV's and we wouldn't want everyone to be an `Admin`.
2. How would you implement the password reset? btw, we have an open ticket for that functionality.
3. We should probably wait with the mentorship component for now but I like where this is going.
